[build-system]
requires = ["scikit-build-core>=0.9"]
build-backend = "scikit_build_core.build"

[project]
name = "mlir-laksa"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = ["PyYAML>=5.4.0,<=6.0.3"]

[project.scripts]
laksa-merge-profiles = "laksa_tools.mocasin.merge_profiles:main"

[tool.scikit-build]
build-dir = "build"
cmake.build-type = "Release"
build.targets = ["LAKSAPythonModules"]
install.components = ["LAKSAPythonModules"]
wheel.packages = ["python/laksa_tools"]

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "CMakeLists.txt"
regex = 'project\(laksa\s+VERSION\s+(?P<value>\d+\.\d+\.\d+)'

[tool.scikit-build.cmake.define]
MLIR_ENABLE_BINDINGS_PYTHON = "ON"
MLIR_PYTHON_PACKAGE_PREFIX = "mlir_laksa"
MLIR_BINDINGS_PYTHON_INSTALL_PREFIX = "mlir_laksa"
MLIR_BINDINGS_PYTHON_NB_DOMAIN = "mlir_laksa"
BUILD_SHARED_LIBS = "OFF"
MLIR_BUILD_MLIR_C_DYLIB = "OFF"

[tool.scikit-build.editable]
mode = "redirect"
