################################################################################
# FuncExtIncGen
#
# MLIR Func dialect extension generated includes.
################################################################################

add_custom_target(FuncExtIncGen)

# Passes
add_subdirectory(Transforms)
