################################################################################
# LinalgExtIncGen
#
# MLIR Linalg dialect extension generated includes.
################################################################################

add_custom_target(LinalgExtIncGen)

# Passes
add_subdirectory(Transforms)
